-- Generated by Matugen. Do not edit manually.

hl.config({
    general = {
        col = {
            active_border = {
                colors = {
                    "rgba({{colors.primary.default.hex_stripped}}ff)",
                    "rgba({{colors.tertiary.default.hex_stripped}}ee)",
                },
                angle = 45,
            },

            inactive_border =
                "rgba({{colors.outline_variant.default.hex_stripped}}99)",
        },
    },

    decoration = {
        shadow = {
            color = 0xaa{{colors.shadow.default.hex_stripped}},
        },
    },
})
