from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
from pathlib import Path
from typing import Any

from settings_core import (
    FUZZEL_CONFIG,
    HOME,
    HYPR_OVERRIDE,
    PANEL_DIR,
    PANEL_PARTS,
    PANEL_QML,
    atomic_write,
    current_wallpaper,
    theme_arguments,
)


def lua_bool(value: bool) -> str:
    return "true" if value else "false"


def lua_number(value: int | float) -> str:
    if isinstance(value, int):
        return str(value)
    return f"{value:.3f}".rstrip("0").rstrip(".")


def render_hyprland(settings: dict[str, Any]) -> str:
    layout = settings["layout"]
    effects = settings["effects"]
    input_settings = settings["input"]
    return f'''--------------------------------
-- Generated user settings
--------------------------------

-- Do not edit this file directly. Use Super + comma.

local gamingState =
    (os.getenv("XDG_RUNTIME_DIR") or "/tmp")
    .. "/aarav-gamemode"

local gamingMode = io.open(gamingState, "r")

if gamingMode then
    gamingMode:close()
else
    hl.config({{
        general = {{
            gaps_in = {lua_number(layout["gaps_in"])},
            gaps_out = {lua_number(layout["gaps_out"])},
            border_size = {lua_number(layout["border_size"])},
        }},
        decoration = {{
            rounding = {lua_number(layout["rounding"])},
            active_opacity = {lua_number(layout["active_opacity"])},
            inactive_opacity = {lua_number(layout["inactive_opacity"])},
            dim_inactive = {lua_bool(effects["dim_inactive"])},
            dim_strength = {lua_number(effects["dim_strength"])},
            shadow = {{
                enabled = {lua_bool(effects["shadow_enabled"])},
                range = {lua_number(effects["shadow_range"])},
                render_power = {lua_number(effects["shadow_power"])},
                color = 0x88000000,
            }},
            blur = {{
                enabled = {lua_bool(effects["blur_enabled"])},
                size = {lua_number(effects["blur_size"])},
                passes = {lua_number(effects["blur_passes"])},
                vibrancy = {lua_number(effects["blur_vibrancy"])},
            }},
        }},
        animations = {{
            enabled = {lua_bool(effects["animations_enabled"])},
        }},
        input = {{
            follow_mouse = {1 if input_settings["follow_mouse"] else 0},
            sensitivity = {lua_number(input_settings["sensitivity"])},
        }},
    }})
end
'''


def replace_ini_value(text: str, section: str, key: str, value: str) -> str:
    pattern = re.compile(rf"(?ms)^\[{re.escape(section)}\]\s*$.*?(?=^\[|\Z)")
    match = pattern.search(text)
    if not match:
        return text.rstrip() + f"\n\n[{section}]\n{key}={value}\n"
    block = match.group(0)
    key_pattern = re.compile(rf"(?m)^{re.escape(key)}=.*$")
    if key_pattern.search(block):
        updated = key_pattern.sub(f"{key}={value}", block, count=1)
    else:
        updated = block.rstrip() + f"\n{key}={value}\n\n"
    return text[:match.start()] + updated + text[match.end():]


def apply_launcher(settings: dict[str, Any]) -> None:
    if not FUZZEL_CONFIG.is_file():
        return
    launcher = settings["launcher"]
    text = FUZZEL_CONFIG.read_text()
    main = {
        "font": f'Noto Sans:size={launcher["font_size"]},Symbols Nerd Font Mono:size={launcher["font_size"]}',
        "width": str(launcher["width"]),
        "lines": str(launcher["lines"]),
        "horizontal-pad": str(launcher["horizontal_pad"]),
        "vertical-pad": str(launcher["vertical_pad"]),
        "inner-pad": str(launcher["inner_pad"]),
        "line-height": f'{launcher["line_height"]}px',
    }
    border = {
        "radius": str(launcher["radius"]),
        "selection-radius": str(launcher["selection_radius"]),
    }
    for key, value in main.items():
        text = replace_ini_value(text, "main", key, value)
    for key, value in border.items():
        text = replace_ini_value(text, "border", key, value)
    atomic_write(FUZZEL_CONFIG, text)

    fuzzel = shutil.which("fuzzel")
    if fuzzel:
        result = subprocess.run(
            [fuzzel, "--check-config"], check=False, capture_output=True, text=True
        )
        if result.returncode != 0:
            raise RuntimeError(result.stderr.strip() or "Fuzzel rejected its config")


def apply_hyprland(settings: dict[str, Any]) -> None:
    atomic_write(HYPR_OVERRIDE, render_hyprland(settings), mode=0o644)


def reload_hyprland() -> None:
    hyprctl = shutil.which("hyprctl")
    if hyprctl:
        subprocess.run(
            [hyprctl, "reload"], check=False,
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        )


def apply_components(settings: dict[str, Any], component: str) -> None:
    if component in {"all", "hyprland"}:
        apply_hyprland(settings)
    if component in {"all", "launcher"}:
        apply_launcher(settings)
    if component in {"all", "hyprland"}:
        reload_hyprland()


def retheme_current(settings: dict[str, Any]) -> bool:
    wallpaper = current_wallpaper()
    matugen = shutil.which("matugen")
    if wallpaper is None or matugen is None:
        return False
    result = subprocess.run(
        [matugen, "image", str(wallpaper), *theme_arguments(settings)], check=False
    )
    if result.returncode != 0:
        raise RuntimeError("Matugen failed while applying the saved theme settings")
    return True


def assemble_panel() -> None:
    if not PANEL_PARTS:
        raise RuntimeError("Settings panel source parts are missing")
    content = "".join(path.read_text() for path in PANEL_PARTS)
    if not content.startswith("//@ pragma AppId aarav-settings"):
        raise RuntimeError("Settings panel source is incomplete")
    atomic_write(PANEL_QML, content, mode=0o644)


def open_panel(settings: dict[str, Any]) -> None:
    apply_components(settings, "all")
    assemble_panel()
    hyprctl = shutil.which("hyprctl")
    if hyprctl:
        clients = subprocess.run(
            [hyprctl, "clients", "-j"], check=False, capture_output=True, text=True
        )
        if clients.returncode == 0:
            try:
                payload = json.loads(clients.stdout)
            except json.JSONDecodeError:
                payload = []
            for client in payload if isinstance(payload, list) else []:
                if isinstance(client, dict) and client.get("class") == "aarav-settings":
                    address = str(client.get("address", "")).strip()
                    if address:
                        subprocess.run(
                            [hyprctl, "dispatch", "focuswindow", f"address:{address}"],
                            check=False, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                        )
                        return

    qs = shutil.which("qs")
    if qs is None:
        raise RuntimeError("Quickshell command 'qs' is unavailable")
    if not PANEL_QML.is_file():
        raise RuntimeError(f"Settings panel is missing: {PANEL_QML}")
    environment = os.environ.copy()
    environment["QS_DISABLE_FILE_WATCHER"] = "1"
    subprocess.Popen(
        [qs, "-p", str(PANEL_QML)], cwd=PANEL_DIR, env=environment,
        stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL, start_new_session=True,
    )
