-- Generated by Matugen. Do not edit manually.

hl.config({
    general = {
        col = {
            active_border = {
                colors = {
                    "rgba(ffb598ff)",
                    "rgba(8fd4c3ee)",
                },
                angle = 45,
            },

            inactive_border =
                "rgba(4e5f5999)",
        },
    },

    decoration = {
        shadow = {
            color = 0xaa000000,
        },
    },
})
